### ISSUE TITLE
No installing Node > 10

### ISSUE THREAD

**Issue by URBANsUNITED** [marvinroger/node-rcswitch#15]
Hi!

I am not able to install rcswitch with Node greater then V 10
Here is the log from using the latest dev version:

```
sudo npm install -g --unsafe-perm

> rcswitch@0.3.1 install /usr/local/lib/node_modules/rcswitch
> node-gyp rebuild

make: Verzeichnis „/home/pi/node-rcswitch/build“ wird betreten
  CXX(target) Release/obj.target/rcswitch/src/rcswitch.o
  CXX(target) Release/obj.target/rcswitch/src/RCSwitchNode.o
../src/RCSwitchNode.cpp: In static member function ‘static void RCSwitchNode::New(const Nan::FunctionCallbackInfo<v8::Value>&)’:
../src/RCSwitchNode.cpp:92:59: error: no matching function for call to ‘v8::Function::NewInstance(const int&, v8::Local<v8::Value> [0])’
     info.GetReturnValue().Set(cons->NewInstance(argc, argv));
                                                           ^
In file included from /root/.node-gyp/10.5.0/include/node/node.h:63:0,
                 from ../node_modules/nan/nan.h:51,
                 from ../src/RCSwitchNode.h:4,
                 from ../src/RCSwitchNode.cpp:1:
/root/.node-gyp/10.5.0/include/node/v8.h:3911:44: note: candidate: v8::MaybeLocal<v8::Object> v8::Function::NewInstance(v8::Local<v8::Context>, int, v8::Local<v8::Value>*) const
   V8_WARN_UNUSED_RESULT MaybeLocal<Object> NewInstance(
                                            ^~~~~~~~~~~
/root/.node-gyp/10.5.0/include/node/v8.h:3911:44: note:   candidate expects 3 arguments, 2 provided
/root/.node-gyp/10.5.0/include/node/v8.h:3914:44: note: candidate: v8::MaybeLocal<v8::Object> v8::Function::NewInstance(v8::Local<v8::Context>) const
   V8_WARN_UNUSED_RESULT MaybeLocal<Object> NewInstance(
                                            ^~~~~~~~~~~
/root/.node-gyp/10.5.0/include/node/v8.h:3914:44: note:   candidate expects 1 argument, 2 provided
rcswitch.target.mk:99: die Regel für Ziel „Release/obj.target/rcswitch/src/RCSwitchNode.o“ scheiterte
make: *** [Release/obj.target/rcswitch/src/RCSwitchNode.o] Fehler 1
make: Verzeichnis „/home/pi/node-rcswitch/build“ wird verlassen
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Linux 4.14.34-v7+
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/pi/node-rcswitch
gyp ERR! node -v v10.5.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rcswitch@0.3.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the rcswitch@0.3.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-06-27T18_22_11_648Z-debug.log
```

**Comment by p33k** [comment]
+1

**Comment by fisch55** [comment]
+1

**Comment by nervalo88** [comment]
Issue reproduced, 

Not OK with node10.16.2

```pi@RpiNodeZero:~/nodeJS $ sudo npm i -g rcswitch

> rcswitch@0.3.1 install /usr/local/lib/node_modules/rcswitch
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/10.16.2"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/rcswitch/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/rcswitch/.node-gyp'
gyp ERR! System Linux 4.19.58-v7+
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/rcswitch
gyp ERR! node -v v10.16.2
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rcswitch@0.3.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the rcswitch@0.3.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-08-14T20_21_30_927Z-debug.log
```
fine with node 8.16.0
```
/node-raspi-rcswitch-api $ npm install

> rcswitch@0.3.1 install /home/pi/nodeJS/node-raspi-rcswitch-api/node_modules/rcswitch
> node-gyp rebuild

make : on entre dans le répertoire « /home/pi/nodeJS/node-raspi-rcswitch-api/node_modules/rcswitch/build »
  CXX(target) Release/obj.target/rcswitch/src/rcswitch.o
  CXX(target) Release/obj.target/rcswitch/src/RCSwitchNode.o
../src/RCSwitchNode.cpp: In static member function ‘static void RCSwitchNode::New(const Nan::FunctionCallbackInfo<v8::Value>&)’:
../src/RCSwitchNode.cpp:83:59: warning: ‘v8::Local<v8::Object> v8::Function::NewInstance(int, v8::Local<v8::Value>*) const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
     info.GetReturnValue().Set(cons->NewInstance(argc, argv));
                                                           ^
In file included from /home/pi/.node-gyp/8.16.0/include/node/v8.h:26:0,
                 from /home/pi/.node-gyp/8.16.0/include/node/node.h:63,
                 from ../../nan/nan.h:54,
                 from ../src/RCSwitchNode.h:4,
                 from ../src/RCSwitchNode.cpp:1:
/home/pi/.node-gyp/8.16.0/include/node/v8.h:3897:31: note: declared here
                 Local<Object> NewInstance(int argc, Local<Value> argv[]) const);
                               ^
/home/pi/.node-gyp/8.16.0/include/node/v8config.h:318:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
  CXX(target) Release/obj.target/rcswitch/externals/rcswitch-pi/RCSwitch.o
  SOLINK_MODULE(target) Release/obj.target/rcswitch.node
  COPY Release/rcswitch.node
make : on quitte le répertoire « /home/pi/nodeJS/node-raspi-rcswitch-api/node_modules/rcswitch/build »
npm notice created a lockfile as package-lock.json. You should commit this file.
added 3 packages from 2 contributors and audited 149 packages in 17.246s
found 0 vulnerabilities
```

The package `[sudo] npm i n -g` makes swaping node version easily !

**Comment by MaKnoNet** [comment]
**RCSwitchNode.cpp**


![grafik](https://user-images.githubusercontent.com/59054437/71569553-2cb75d00-2ad0-11ea-87fb-bdbb95c95ee1.png)

After I commented it out, it worked or replace it with this code:

info.GetReturnValue().Set(Nan::NewInstance(cons, argc, argv).ToLocalChecked());

**Comment by meyer-roessl** [comment]
+1

**Comment by c-klinger** [comment]
I had the same issue and commited a pull request with a fix. Until it is accpted the following can be used as workaround (references my fork with the changes)

```
  "dependencies": {
    "rcswitch": "git://github.com/c-klinger/node-rcswitch.git#d4f2ded",
  },
```
