### ISSUE TITLE
Cannot compile

### ISSUE THREAD

**Issue by coolchip** [marvinroger/node-rcswitch#9]
```
../externals/rcswitch-pi/RCSwitch.cpp: In Elementfunktion »char* RCSwitch::getCodeWordB(int, int, boolean)«:
../externals/rcswitch-pi/RCSwitch.cpp:196:12: Fehler: ungültige Umwandlung von »char« in »char*« [-fpermissive]
     return '\0';
            ^~~~
../externals/rcswitch-pi/RCSwitch.cpp: In Elementfunktion »char* RCSwitch::getCodeWordA(char*, int, boolean)«:
../externals/rcswitch-pi/RCSwitch.cpp:232:14: Fehler: ungültige Umwandlung von »char« in »char*« [-fpermissive]
       return '\0';
              ^~~~
../externals/rcswitch-pi/RCSwitch.cpp:241:14: Fehler: ungültige Umwandlung von »char« in »char*« [-fpermissive]
       return '\0';
              ^~~~
../externals/rcswitch-pi/RCSwitch.cpp: In Elementfunktion »char* RCSwitch::getCodeWordC(char, int, int, boolean)«:
../externals/rcswitch-pi/RCSwitch.cpp:269:12: Fehler: ungültige Umwandlung von »char« in »char*« [-fpermissive]
     return '\0';
            ^~~~
make: *** [rcswitch.target.mk:97: Release/obj.target/rcswitch/externals/rcswitch-pi/RCSwitch.o] Fehler 1
make: Verzeichnis „/home/sebastian/temp/node-rcswitch/build“ wird verlassen
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:197:12)
gyp ERR! System Linux 4.9.30-1-ARCH
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/sebastian/temp/node-rcswitch
gyp ERR! node -v v8.1.0
gyp ERR! node-gyp -v v3.6.2

```

**Comment by coolchip** [comment]
Hey, I send you a pull request #10 . This will fix this issue.

**Comment by marvinroger** [comment]
5 years after (I'm sorry), I'm closing this as this is fixed by https://github.com/marvinroger/node-rcswitch/pull/12
